### PR TITLE
Fix bug error 500 returned by c3.php, when dir report is already created

### PR DESCRIPTION
**Pull request by moisemorard**

### CODE REVIEW

**Comment by sergeyklay** [comment]
Looks foot to me. @DavertMik ?

**Comment by 501st-alpha1** [comment]
:+1: This fixes the problem for me.

**Comment by neoascetic** [comment]
Looks good to me, although the same approach need to be applied to errors logging. @moisemorard can you please add it too? Thanks!

**Comment by neronmoon** [comment]
+1

**Pull request merged**
