### PR TITLE
Composer 2.0 compatibility

### PR DESCRIPTION
**Pull request by mwi-gofore**
Seems to work fine with Composer 2.0, and "should" not break Composer 1.x compatibility.

### CODE REVIEW

**Comment by mwi-gofore** [comment]
Got zero experience with Travis, but trying to see if we can get the tests to run using both 1.x and 2.x versions of composer.

**Comment by vctls** [comment]
Thank you for this!
Is the build stuck or something? I think it's been doing nothing for half an hour already.

**Comment by mwi-gofore** [comment]
> Thank you for this!
> Is the build stuck or something? I think it's been doing nothing for half an hour already.
> 
> Edit: nevermind, it just passed some more jobs. Just taking it's time, apparently.

Yea. Looks strange.. Did some googling, and apparently that happens to other builds also.. Thought it was related to the backgrounded PHP process, but looks like it's killed immediately after the codeception run...

**Comment by Slamdunk** [comment]
🚢 🚀

**Review by samdark — APPROVED** [review]

**Comment by Naktibalda** [comment]
Merged and released. Please test 2.6.0

**Comment by vctls** [comment]
Works for me 😊

**Comment by Slamdunk** [comment]
I can confirm too :+1:

**Comment by Naktibalda** [comment]
@mwi-gofore Please take a look at #63

**Pull request merged**
