### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ksiv**
Save a lot of trouble for people who going to use it

### CODE REVIEW

**Comment by samdark** [comment]
Which trouble?

**Comment by Naktibalda** [comment]
I think that README should explain that the last 2 lines of that example is an example of the code which was present in index.php before adding c3.php.

**Comment by ksiv** [comment]
Now I know that it's two lines,  not the last one :-)

**Comment by ksiv** [comment]
Thanks for quick answer, on some repos there is not any :-) I m currently improving experience of Codeception usage in one project. There are two points so far preventing  me from out -of-the-box remote code coverage.

**Comment by DavertMik** [comment]
Just one word. LOL

**Pull request merged**
